### ISSUE TITLE
SAML2 SingleLogout - if not logout configured get an NPE

### ISSUE THREAD

**Issue by mlbiam** [TremoloSecurity/OpenUnison#44]
javax.servlet.ServletException: Could not generate logout request
	at com.tremolosecurity.proxy.auth.saml2.Saml2SingleLogout.handleLogout(Saml2SingleLogout.java:211)
	at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:301)
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93)
	at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:272)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: Signing Key : '' not found
	at com.tremolosecurity.proxy.auth.saml2.Saml2SingleLogout.handleLogout(Saml2SingleLogout.java:191)
	... 21 more

**Comment by mlbiam** [comment]
This is a non issue, the key wasn't configured
