### ISSUE TITLE
Proxying to Kubernetes Dashboard (v7) over HTTPS (using self-signed certificate) fails

### ISSUE THREAD

**Issue by spantaleev** [TremoloSecurity/OpenUnison#877]
This is either some misconfiguration on my end or a regression with the new Kubernetes Dashboard ([v7.0.0](https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0)), which started using Kong as a reverse-proxy that fronts all Kubernetes Dashboard services.

## Kubernetes Dashboard

I'm installing Kubernetes Dashboard via ArgoCD like this:

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubernetes-dashboard
    name: in-cluster
  source:
    repoURL: 'https://kubernetes.github.io/dashboard'
    targetRevision: 7.3.2
    helm:
      values: |
        kong:
          proxy:
            http:
              enabled: true
    chart: kubernetes-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources: []
  project: common
```

By default, Kubernetes Dashboard is meant to be served via its `kubernetes-dashboard-kong-proxy` service - see [its ingress](https://github.com/kubernetes/dashboard/blob/dde23c41c6ee7e85194dc897cf73ee0f781f7d99/charts/kubernetes-dashboard/templates/networking/ingress.yaml#L84), which proxies to an HTTPS backend.

The `kubernetes-dashboard-kong-proxy` service is created by the [Kong subchart](https://artifacthub.io/packages/helm/kong/kong). This chart defaults to exposing the server over both HTTP (see [`proxy.http.enabled`](https://artifacthub.io/packages/helm/kong/kong?modal=values&path=proxy.http.enabled)) and HTTPS (see [`proxy.tls.enabled`](https://artifacthub.io/packages/helm/kong/kong?modal=values&path=proxy.tls.enabled)). However, Kubernetes Dashboard [defaults `proxy.http.enabled` to `false`](https://github.com/kubernetes/dashboard/blob/dde23c41c6ee7e85194dc897cf73ee0f781f7d99/charts/kubernetes-dashboard/values.yaml#L360).

With the above overrides, I'm enabling the plain-HTTP listener, because I'm trying to make OpenUnison use that one instead of the HTTPS one. More on this attempt to fix things, below.

------

## OpenUnison

As described in the OpenUnison docs, I'm not enabling Kubernetes Dashboard's ingress.

I'm relying on OpenUnison to create an ingress and reverse-proxy to the `kubernetes-dashboard-kong-proxy` service.

I'm installing OpenUnison via ArgoCD with the following application:

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openunison
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
    - /webhooks/2/clientConfig/caBundle
    - /webhooks/3/clientConfig/caBundle
    - /webhooks/4/clientConfig/caBundle
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
  source:
    repoURL: 'https://nexus.tremolo.io/repository/helm'
    targetRevision: 2.3.54
    helm:
      values: |-
        network:
          openunison_host: "console.DOMAIN"
          dashboard_host: "dashboard.DOMAIN"
          api_server_host: "api.DOMAIN"
          session_inactivity_timeout_seconds: 900

          k8s_url: https://DOMAIN:6443

          force_redirect_to_tls: false
          createIngressCertificate: false
          ingress_type: nginx
          ingress_annotations:
            cert-manager.io/cluster-issuer: letsencrypt-live

        cert_template:
          ou: "Kubernetes"
          o: "MyOrg"
          l: "My Cluster"
          st: "State of Cluster"
          c: "MyCountry"

        myvd_config_path: "WEB-INF/myvd.conf"
        k8s_cluster_name: my-cluster
        enable_impersonation: true

        impersonation:
          use_jetstack: true
          explicit_certificate_trust: true

        dashboard:
          namespace: "kubernetes-dashboard"
          cert_name: "kubernetes-dashboard-tls"
          label: "k8s-app=kubernetes-dashboard"
          service_name: kubernetes-dashboard-kong-proxy
          require_session: true

        certs:
          use_k8s_cm: false

        trusted_certs: []

        monitoring:
          prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

        oidc:
         client_id: openunison
         issuer: https://keycloak.DOMAIN/realms/REALM
         user_in_idtoken: true
         domain: ""
         scopes: openid email profile groups
         claims:
           sub: sub
           email: email
           given_name: given_name
           family_name: family_name
           display_name: name
           groups: groups

        network_policies:
          enabled: false
          ingress:
            enabled: true
            labels:
              kubernetes.io/metadata.name: ingress-nginx-internet
          monitoring:
            enabled: true
            labels:
              kubernetes.io/metadata.name: monitoring
          apiserver:
            enabled: true
            labels:
              kubernetes.io/metadata.name: kube-system

        services:
          enable_tokenrequest: false
          token_request_audience: api
          token_request_expiration_seconds: 600
          node_selectors: []

        openunison:
          replicas: 1
          non_secret_data:
            K8S_DB_SSO: oidc
            PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k8s

          secrets: []
          html:
            prefix: openunison
          enable_provisioning: false
          az_groups: [Kubernetes-Developer, Kubernetes-SuperAdministrator]
    chart: orchestra-login-portal-argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openunison
```

As a result of deploying, a `dashboard` CRD application is created that looks like this:

```yml
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '30'
  labels:
    app.kubernetes.io/component: openunison-applications
    app.kubernetes.io/instance: openunison-openunison
    app.kubernetes.io/name: openunison
    app.kubernetes.io/part-of: openunison
    argocd.argoproj.io/instance: openunison
  name: dashboard
  namespace: openunison
spec:
  azTimeoutMillis: 3000
  cookieConfig:
    cookiesEnabled: true
    domain: dashboard.DOMAIN
    httpOnly: true
    keyAlias: session-unison
    logoutURI: /logout
    scope: -1
    secure: true
    sessionCookieName: tremolosession
    timeout: 900
  isApp: true
  urls:
    - authChain: k8s-db-oidc
      azRules:
        - constraint: (groups=Kubernetes-Developer)
          scope: filter
        - constraint: (groups=Kubernetes-SuperAdministrator)
          scope: filter
      filterChain:
        - className: com.tremolosecurity.proxy.filters.SetNoCacheHeaders
          params: {}
        - className: com.tremolosecurity.proxy.filters.AzFilter
          params:
            azFail: force-logout
            rules:
              - custom;require-session
        - className: com.tremolosecurity.proxy.filters.K8sInjectImpersonation
          params:
            groupAttribute: groups
            targetName: k8s
            useLdapGroups: 'false'
            userNameAttribute: sub
      hosts:
        - dashboard.DOMAIN
      overrideHost: true
      overrideReferer: true
      proxyTo: >-
        https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc${fullURI}
      results:
        auFail: default-login-failure
        azFail: default-login-failure
      uri: /
    - authChain: anon
      azRules:
        - constraint: o=Tremolo
          scope: dn
      filterChain:
        - className: com.tremolosecurity.prelude.filters.StopProcessing
          params: {}
      hosts:
        - dashboard.DOMAIN
      results:
        azSuccess: logout
      uri: /logout
```

In `proxyTo`, I see `https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc` which is a valid URL. This reaches Kong on its TLS port which uses a self-signed certificate.

## Result

When trying to access the dashboard, I see this in the logs for `openunison-openunison`:

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148) ~[?:?]
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129) ~[?:?]
    at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
    at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
    at java.base/sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
    at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313) ~[?:?]
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222) ~[?:?]
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129) ~[?:?]
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
    at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) ~[?:?]
    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) ~[?:?]
    at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183) ~[?:?]
    at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
    at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511) ~[?:?]
    at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456) ~[?:?]
    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427) ~[?:?]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar:4.5.14]
    at com.tremolosecurity.proxy.postProcess.UriRequestProcess.postProcess(UriRequestProcess.java:127) ~[unison-server-core-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filter.HttpFilterChainImpl.nextFilter(HttpFilterChainImpl.java:91) ~[unison-sdk-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filters.K8sInjectImpersonation.doFilter(K8sInjectImpersonation.java:92) ~[unison-applications-k8s-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filter.HttpFilterChainImpl.nextFilter(HttpFilterChainImpl.java:85) ~[unison-sdk-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filters.AzFilter.doFilter(AzFilter.java:95) ~[unison-server-core-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filter.HttpFilterChainImpl.nextFilter(HttpFilterChainImpl.java:85) ~[unison-sdk-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filters.SetNoCacheHeaders.doFilter(SetNoCacheHeaders.java:25) ~[unison-server-core-1.0.40.jar:?]
    at com.tremolosecurity.proxy.filter.HttpFilterChainImpl.nextFilter(HttpFilterChainImpl.java:85) ~[unison-sdk-1.0.40.jar:?]
    at com.tremolosecurity.proxy.ProxySys.doURI(ProxySys.java:97) ~[unison-server-core-1.0.40.jar:?]
    ... 43 more
```

I suspect that this is because OpenUnison does not like the self-signed certificate presented by Kong at `https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc`.

I'm not sure what `dashboard.cert_name` should be set to for the OpenUnison ArgoCD chart and whether that could help.

## Workaround

If I modify the `dashboard` application resource manually like this:

```diff
       proxyTo: >-
-        https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc${fullURI}
+        http://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc:80${fullURI}
```

.. it starts working.

This requires deploying the Kubernetes Dashboard chart with a `proxy.http.enabled=true` override (as described above).

## Thoughts

Unless I've done something wrong, I suppose this is caused by a recent change in Kubernetes Dashboard and possibly affects everyone.

It'd be nice if OpenUnison could be:

- either: made to trust self-signed certificates when proxying (perhaps using a new [`proxyConfiguration` option](https://github.com/OpenUnison/helm-charts/blob/525f9cb674453796c33816d1bee89f3e6b2e9374/orchestra-login-portal/templates/openunison/applications/dashboard.yaml#L46))
- or: made configuring the protocol used in `proxyTo` in [orchestra-login-portal/templates/openunison/applications/dashboard.yaml](https://github.com/OpenUnison/helm-charts/blob/525f9cb674453796c33816d1bee89f3e6b2e9374/orchestra-login-portal/templates/openunison/applications/dashboard.yaml#L44) possible

Perhaps something like this?

```diff
     uri: "/"
-    proxyTo: https://{{ .Values.dashboard.service_name }}.{{ .Values.dashboard.namespace }}.svc${fullURI}
+    proxyTo: {{ .Values.dashboard.scheme }}://{{ .Values.dashboard.service_name }}.{{ .Values.dashboard.namespace }}.svc${fullURI}

**Comment by mlbiam** [comment]
> This is either some misconfiguration on my end or a regression with the new Kubernetes Dashboard ([v7.0.0](https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0)), which started using Kong as a reverse-proxy that fronts all Kubernetes Dashboard services.

I haven't tested yet with v7 chart because it's the 3.0 dashboard which introduced some pretty fundamental changes in the ay its setup.

I would recommend the 6.8 chart, but if you want to work with 7.x I'll be happy to work through it with you.

> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

If you're deployed with Kong which has its own cert, you'll need to add it to the values file in the `trusted_certs` section - https://openunison.github.io/knowledgebase/certificates/ has an example at the bottom.  Just don't name it `unison-ca` (unless that's the same CA that is hosting OpenUnison's cert)

**Comment by spantaleev** [comment]
Thank you for the hints - they got me to a working solution! :bow: 

I wasn't sure how to extract Kong's [auto-generated SSL certificate](https://docs.konghq.com/gateway/3.6.x/reference/configuration/#ssl_cert) and how stable it would be over time, so I thought it'd be better to use an externally-managed SSL certificate.

Looks like OpenUnison had already generated such an SSL certificate (thanks to the [`dashboard.cert_name` configuration value](https://github.com/OpenUnison/helm-charts/blob/525f9cb674453796c33816d1bee89f3e6b2e9374/orchestra-login-portal-argocd/values.yaml#L29)). It also seems like OpenUnison already trusts this SSL certificate by default, so it'd be easiest to make Kong use it and avoid whitelisting additional certificates in OpenUnison's `trusted_certs`.

Making Kong use such a custom SSL certificate (stored in the `kubernetes-dashboard-tls` secret) can be accomplished with the following values for Kubernetes Dashboard's Helm chart:

```yml
kong:
  secretVolumes:
    - kubernetes-dashboard-tls
  customEnv:
    KONG_SSL_CERT: /etc/secrets/kubernetes-dashboard-tls/dashboard.crt
    KONG_SSL_CERT_KEY: /etc/secrets/kubernetes-dashboard-tls/dashboard.key
```

------

I'll close this issue now, but feel free to re-open it if it would serve as a reminder to test this more and/or update the docs with instructions for this new Kubernetes Dashboard version.

**Comment by mlbiam** [comment]
That'll be very useful when I update the charts to support the latest dashboard.  They made some major architectural changes that will need us to update our integration.  

> Looks like OpenUnison had already generated such an SSL certificate

Yes, that way we can do end2end encryption.  We also make sure to re-create them a month before expiration.
